service: projeto-base-serverless

provider:
  name: aws
  runtime: nodejs16.x

configValidationMode: error

functions: ${file(./src/functions/functions.yaml)}

plugins:
  - serverless-offline

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node16